import { ROUTES } from './routes';

export type Role =
  | 'ADMIN'
  | 'MANAGER'
  | 'VENDOR'
  | 'PROPERTY_OWNER'
  | 'CUSTOMER';

export const NAV_ACCESS: Record<Role, string[]> = {
  ADMIN: [
    ROUTES.DASHBOARD,

    // Admin
    ROUTES.ADMIN.ROOT,
    ROUTES.ADMIN.AUDIT,
    ROUTES.ADMIN.REPORTS,
    ROUTES.ADMIN.SETTINGS,
    ROUTES.ADMIN.USERS,
    ROUTES.ADMIN.CUSTOMERS,

    // Manager (admin can view)
    ROUTES.MANAGER.ROOT,
    ROUTES.MANAGER.WORK,
    ROUTES.MANAGER.LEASING,
    ROUTES.MANAGER.PAYMENTS,
    ROUTES.MANAGER.TICKETS,
    ROUTES.MANAGER.EMPLOYER_MGMT,
    ROUTES.MANAGER.EMPLOYER_SALARY,
    ROUTES.MANAGER.SETTINGS,
  

    // Vendor
    ROUTES.VENDOR.ROOT,
    ROUTES.VENDOR.SETTINGS,
    ROUTES.VENDOR.JOBS,
  ],

  MANAGER: [
    ROUTES.DASHBOARD,

    ROUTES.MANAGER.ROOT,
    ROUTES.MANAGER.WORK,
    ROUTES.MANAGER.LEASING,
    ROUTES.MANAGER.PAYMENTS,
    ROUTES.MANAGER.TICKETS,
    ROUTES.MANAGER.EMPLOYER_MGMT,
    ROUTES.MANAGER.EMPLOYER_SALARY,
    ROUTES.MANAGER.SETTINGS,
    ROUTES.MANAGER.CUSTOMERS,
  ],

  CUSTOMER: [
    ROUTES.DASHBOARD,
    ROUTES.MANAGER.CUSTOMERS, // OR admin customers if you want
  ],

  VENDOR: [
    ROUTES.DASHBOARD,
    ROUTES.VENDOR.ROOT,
    ROUTES.VENDOR.SETTINGS,
    ROUTES.VENDOR.JOBS,
  ],

  PROPERTY_OWNER: [
    ROUTES.DASHBOARD,
  ],
};
